#!/bin/env bash

QCG_PM_ROOT=/home/plgrid/plgkopta/qcg-pilotmanager


module load python/3.5.1 > /dev/null 2>&1
export PYTHONPATH=$PYTHONPATH:/home/plgrid/plgkopta/qcg-pilotmanager/env/lib/python3.5/:/home/plgrid/plgkopta/qcg-pilotmanager/env/lib/python3.5/site-packages:/home/plgrid/plgkopta/qcg-pilotmanager/qcg-pilotmanager

python $@
