version: '3.3'
services:

  qcg-pilotjob:
    restart: unless-stopped
    image: qcg-pilotjob:develop
    volumes:
      - "${REPO_DIR}/src:/srv/src"
      - "${REPO_DIR}/example-scripts:/srv/example-scripts"

